[package]
name = "solana-build-tool"
version = "0.1.1"
edition = "2021"

[[bin]]
name = "sbt"
path = "src/main.rs"

[dependencies]
cargo_metadata = "0.19.2"
eframe = "0.31.0"
rfd = "0.15.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
